---
- name: Copy new_nats.conf to target hosts
  hosts: all
  become: true  # Run tasks with root privileges
  gather_facts: no
  vars:
    root_password: "{{ root_password }}"
  tasks:
    - name: Copy nats config
      copy:
        src: new_nats.conf  # Local path to new_nats.conf
        dest: /root/nats.conf
    - name: copy nats server
      copy:
        src: nats-server-v2.10.18-amd64.deb
        dest: /root/nats-server-v2.10.18-amd64.deb
    - name: install nats server
      command: "dpkg -i /root/nats-server-v2.10.18-amd64.deb"
