---
- name: Start Docker container
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Start edge trader app
      docker_container:
        name: edgetrader
        image: brianapley/edge-trader
        pull: true
        state: started
        recreate: true
        interactive: yes
        etc_hosts:
          host.docker.internal: 172.17.0.1
        tty: yes
        ports:
          - "443:443"
        volumes:
          - "aug13a:/data"
          - "/etc:/certs"
          - "/tmp/db:/db"
    - name: Start express server
      docker_container:
        name: nodehttp
        image: brianapley/node-http
        pull: true
        state: started
        recreate: true
        interactive: yes
        tty: yes
        ports:
          - "8443:8443"
        volumes:
          - "/etc:/etc"
          - "/tmp/db:/tmp/db"
