---
- name: Start Docker container
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Start Docker container
      docker_container:
        name: edgetrader
        image: brianapley/edge-trader
        pull: true
        state: started
        recreate: true
        interactive: yes
        etc_hosts:
          host.docker.internal: 172.17.0.1
        tty: yes
        ports:
          - "443:443"
        volumes:
          - "aug12a:/data"
          - "/etc:/certs"
          - "/tmp/db:/db"
