---
- name: Start Docker container
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Start Docker container
      docker_container:
        name: edgetrader
        image: brianapley/edge-trader
        pull: true
        state: started
        recreate: true
        interactive: yes
        add_hosts:
          host.docker.internal: host-gateway
        tty: yes
        ports:
          - "443:443"
        volumes:
          - "aug11:/data"
          - "/etc:/certs"
          - "/tmp/db:/db"
